openapi: 3.0.2
info:
  title: FastAPI
  description: Example app
  version: 0.1.0
paths:
  /items/:
    get:
      tags:
      - Items
      summary: Read Items
      operationId: read_items_items__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Read Items Items  Get
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      tags:
      - Items
      summary: Create Item
      operationId: create_item_items__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Item:
      title: Item
      required:
      - name
      - price
      type: object
      properties:
        name:
          title: Name
          type: string
        price:
          title: Price
          type: number
        short_desc:
          title: Short Desc
          type: string
        description:
          title: Description
          type: string
        tax:
          title: Tax
          type: number
        tags:
          title: Tags
          type: array
          items:
            type: string
          default: []
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
